apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-work-pvc
  namespace: viya4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: managed-csi
